apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sHttpsOnly
metadata:
  name: ingress-https-only
spec:
  match:
    kinds: 
    - apiGroups:
      - extensions
      - networking.k8s.io
      kinds:
      - Ingress