# regelmaat en gelijkheid bij de benamingen van de verschillende service ports die services aanmaken
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedServicePortName
metadata:
  name: port-name-constraint
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Service
  parameters:
    prefixes:
      - http-
      - https-
      - mongo-
      - redis-
      - tcp-
