apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictNamespaces
metadata:
  name: restrict-default-namespace-use
spec:
  enforcementAction: dryrun
  parameters:
    restrictedNamespaces:
    - default
    - kube-system
    - kube-public