# Resource quota's voor alle containers/deployments binnen namespace 2
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerRatios
metadata:
  labels:
    owner: platform-team
  name: hard-limit
  namespace: ns2-team-c
spec:
  containers:
      resources:
        limits:
          cpu: 600m
          memory: 800Mi
        requests:
          cpu: 400m
          memory: 500Mi
