# Resource quota's voor alle containers/deployments binnen namespace 1
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerLimits
metadata:
  name: container-must-have-limits
spec:
  match:
    labelSelector:
      matchLabels: environment:prod
  parameters:
    cpu: 200m
    memory: 1Gi
